BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `categories` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL
);
INSERT INTO `categories` (id,name) VALUES (1,'LEGO Architecture'),
 (2,'Star Wars');
CREATE TABLE IF NOT EXISTS `products` (
 `id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
 `name`	TEXT NOT NULL,
 `price`	REAL NOT NULL,
 `description`	TEXT NOT NULL,
 `spec`	TEXT NOT NULL,
 `img0`	TEXT NOT NULL,
 `img1`	TEXT NOT NULL,
 `img2`	TEXT NOT NULL,
 `img3`	TEXT NOT NULL,
 `id_category`	INTEGER DEFAULT 1 NOT NULL,
 FOREIGN KEY(`id_category`) REFERENCES `categories`(`id`)
);
INSERT INTO `products` (id,name,price,description,spec,img0,img1,img2,img3,id_category) VALUES (1,'New York City',44.99,'<p>Fêtez la diversité architecturale de New York avec ce modèle détaillé en briques LEGO®. La collection LEGO® Architecture Skyline offre des modèles adaptés à l''exposition à la maison et au bureau, et a été développée pour toutes les personnes qui s''intéressent au voyage, à la création, à l''histoire et à l''architecture.</p><p>Chaque ensemble a une échelle adaptée pour donner une idée précise de la taille comparative de chaque structure, avec une représentation en couleurs réaliste. Cet ensemble comprend le Flatiron Building, le Chrysler Building, l''Empire State Building, le One World Trade Center et la Statue de la Liberté, et un écriteau décoratif “New York”.</p>','<ul><li>Interprétation LEGO du paysage de New York.</li><li>Inclut une plaque de base 4x32 avec un écriteau décoratif New York.</li><li>Recréez les plus belles villes du monde avec la collection LEGO Architecture Skyline.</li><li>Mesure 26 cm de haut, 25 cm de large et 4 cm de profondeur.</li></ul>','/images/produit_newyork_0.jpeg','/images/produit_newyork_1.jpeg','/images/produit_newyork_2.jpeg','/images/produit_newyork_3.jpeg',1),
(2,'Millennium Falcon',799.99,'<p>Ce nouveau modèle LEGO® Star Wars Millennium Falcon est le plus grand et le plus détaillé jamais conçu. En réalité, avec ses 7 500 pièces, c’est tout simplement l’un des plus grands modèles LEGO ! Cette fantastique version LEGO de l’inoubliable cargo Corellien de Han Solo présente les moindres détails dont rêvent tous les fans de Star Wars, quel que soit leur âge : d’innombrables détails à l’extérieur, quatre canons laser supérieurs et inférieurs, des pieds d’atterrissage, une rampe d’embarquement qui s’abaisse et un cockpit avec toit amovible pouvant accueillir 4 figurines. Chacune des plaques de la coque peut être retirée pour découvrir les innombrables détails du compartiment principal, le compartiment arrière et le poste d’artillerie. Ce superbe modèle présente également des équipages et des radars interchangeables, ce qui permet aux fans d’opter pour les aventures LEGO Star Wars classiques avec Han, Leia, Chewbacca et C-3PO ou de plonger dans l’univers de l’Episode VII et VIII avec les anciens personnages Han, Rey, Finn et BB-8 !</p>','<ul><li>Inclut 4 figurines de l’équipage classique : Han Solo, Chewbacca, Princesse Leia et C-3PO.Comprend également 3 figurines de l’Épisode VII/VIII : les anciens personnages Han Solo, Rey et Finn.Figurines incluses : un droïde BB-8, ainsi qu’un mynock et 2 Porgs à construire.</li><li>L’extérieur du modèle présente des panneaux de coque amovibles et extrêmement détaillés, une rampe d’embarquement qui s’abaisse, un canon dissimulé, un cockpit pouvant accueillir 4 figurines avec toit amovible, des radars interchangeables (un rond et un rectangulaire), quatre canons laser supérieurs et inférieurs et 7 pieds d’atterrissage.</li><li>Le compartiment principal contient des sièges, l’holojeu Dejarik, un casque d’entraînement à distance au combat, un poste d’ingénierie avec un siège miniature pivotant et une entrée avec passage.</li><li>Le compartiment arrière se compose de la salle des machines avec un hyperdrive et une console, de 2 entrées, d’un compartiment dissimulé dans le sol, de 2 trappes de capsule de sauvetage, d’une console d’ingénierie et d’une échelle permettant d’accéder au poste d’artillerie.</li><li>Le poste d’artillerie présente un siège d’artilleur miniature et un panneau de coque amovible avec quatre canons laser entièrement rotatifs. Quatre autres canons laser sont également montés sur le dessous du modèle.</li><li>Ce modèle comprend 7 500 pièces.</li></ul>','/images/produit_millennium_falcon_0.jpeg','/images/produit_millennium_falcon_1.jpeg','/images/produit_millennium_falcon_2.jpeg','/images/produit_millennium_falcon_3.jpeg',2),
(3,'L''Arc de Triomphe',34.99,'<p>Capturez l’élégance architecturale de l’un des monuments les plus célèbres du monde avec cette impressionnante interprétation LEGO® Architecture de l’Arc de Triomphe. Ce modèle détaillé reproduit fidèlement le célèbre monument emblématique de Paris, avec des piliers ornés de statues, des bas-reliefs sculpturaux et des couleurs subtiles qui ajoutent de la chaleur tout en soulignant les lignes osées, les courbes et les contours du modèle. Il inclut aussi une plaque dorée pour représenter la tombe du Soldat inconnu, une interprétation LEGO de la flamme éternelle et une plaque avec un écriteau « Arc de Triomphe ». Ce modèle en briques LEGO a été conçu pour fournir une expérience de construction stimulante et gratifiante pour toutes les personnes qui s''intéressent au voyage, à la création, à l''histoire et à l''architecture et est adapté à l''exposition à la maison ou au bureau.</p>','<ul><li>Interprétation LEGO® Architecture d''un célèbre bâtiment architectural, l’Arc de Triomphe.</li><li>Comprend des piliers ornés de statues, des bas-reliefs sculpturaux et des couleurs subtiles qui ajoutent de la chaleur et de l’emphase aux lignes, aux courbes et aux contours osés du modèle. Il inclut aussi une plaque dorée pour représenter la tombe du Soldat inconnu et une interprétation LEGO à construire de la flamme éternelle.</li><li>Inclut une plaque décorative avec un écriteau «Arc de Triomphe».</li><li>Livret inclus avec des détails sur la conception, l''architecture et l''histoire du monument (en français et en anglais uniquement. Autres langues disponibles en téléchargement sur LEGO.com/architecture/booklet)</li><li>La ligne de produits LEGO® Architecture célèbre le monde de l''architecture par le biais de la brique LEGO, pour toutes les personnes qui s''intéressent à la création, à l''histoire et à l''architecture.</li><li>Fournit une expérience de construction agréablement stimulante et gratifiante.</li><li>Mesure plus de 11 cm de haut, 14 cm de large et 9 cm de profondeur.</li></ul>','/images/produit_arc_triomphe_0.jpeg','/images/produit_arc_triomphe_1.jpeg','/images/produit_arc_triomphe_2.jpeg','/images/produit_arc_triomphe_3.jpeg',1);
COMMIT;
